apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: service
    spec:
      containers:
        - name: orders
          image: exchange-backedn-orders:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              value: postgres://orders_user:orders_password@postgres-orders:5432/orders_db?sslmode=disable
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
