apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-orders
  labels:
    app.kubernetes.io/name: postgres-orders
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
        app.kubernetes.io/name: postgres-orders
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-orders-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - orders_user
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - orders_user
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          emptyDir: {}
