#!/bin/bash
#
# Generate K8s ConfigMaps for Kong proto files from source protos.
# This ensures proto files have a SINGLE SOURCE OF TRUTH.
#
# Usage: ./scripts/generate-proto-configmap.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

PROTO_DIR="${ROOT_DIR}/proto"
OUTPUT_DIR="${ROOT_DIR}/k8s/infrastructure/kong"
OUTPUT_FILE="${OUTPUT_DIR}/proto-configmap.yaml"
GOOGLE_API_OUTPUT="${OUTPUT_DIR}/google-api-configmap.yaml"

# Proto files to include in ConfigMap (add new services here)
PROTO_FILES=(
    "auth.proto"
    # "orders.proto"  # Uncomment when orders.proto is added
)

echo "Generating K8s ConfigMaps for Kong proto files..."
echo "Source: ${PROTO_DIR}"
echo "Output: ${OUTPUT_FILE}"

# Function to add a proto file to a ConfigMap with proper indentation
add_proto_file() {
    local file_path="$1"
    local key_name="$2"
    local output_file="$3"
    
    if [[ ! -f "${file_path}" ]]; then
        echo "Warning: Proto file not found: ${file_path}" >&2
        return 1
    fi
    
    echo "  Adding: ${key_name}"
    
    # Add the key and pipe the file content with proper indentation
    echo "  ${key_name}: |" >> "${output_file}"
    sed 's/^/    /' "${file_path}" >> "${output_file}"
    echo "" >> "${output_file}"
}

# =============================================================================
# Generate service proto ConfigMap
# =============================================================================

cat > "${OUTPUT_FILE}" << 'EOF'
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-proto-configmap.sh
# To regenerate: make k8s-proto-configmap
#
# This ConfigMap contains proto files for Kong's grpc-gateway plugin.
# The source of truth is the proto/ directory in the repository root.

apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-proto-files
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: gateway
data:
EOF

# Add service proto files
for proto in "${PROTO_FILES[@]}"; do
    add_proto_file "${PROTO_DIR}/${proto}" "${proto}" "${OUTPUT_FILE}"
done

# =============================================================================
# Generate google/api proto ConfigMap (needed for grpc-gateway annotations)
# =============================================================================

cat > "${GOOGLE_API_OUTPUT}" << 'EOF'
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-proto-configmap.sh
# To regenerate: make k8s-proto-configmap
#
# This ConfigMap contains google/api proto files needed by Kong's grpc-gateway.
# These are mounted at /usr/local/kong/include/google/api/

apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-google-api-protos
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: gateway
data:
EOF

add_proto_file "${PROTO_DIR}/google/api/annotations.proto" "annotations.proto" "${GOOGLE_API_OUTPUT}"
add_proto_file "${PROTO_DIR}/google/api/http.proto" "http.proto" "${GOOGLE_API_OUTPUT}"

echo ""
echo "ConfigMaps generated successfully:"
echo "  - ${OUTPUT_FILE}"
echo "  - ${GOOGLE_API_OUTPUT}"
echo ""
echo "Apply with:"
echo "  kubectl apply -f ${OUTPUT_FILE}"
echo "  kubectl apply -f ${GOOGLE_API_OUTPUT}"
